rabbitmq:
  host: "127.0.0.1"
  port: 5672
  user: "guest"
  password: "guest"
  virtual-host: "testing"

lily:
  tex-to-pdf:
    queue-name: "tex2pdf"
    callback-url: "http://localhost:8080/md2pdf/callback"
