# - name: "local compile"
#   hosts: localhost
#   connection: local
#   tasks:
#     - name: "install dashboard dependencies"
#       ansible.builtin.shell:
#         cmd: yarn install
#         chdir: "{{ playbook_dir }}/../dashboard"
#     - name: "build dashboard"
#       ansible.builtin.shell:
#         cmd: NODE_OPTIONS="--max_old_space_size=4096" PUBLIC_URL=/pcd yarn build
#         chdir: "{{ playbook_dir }}/../dashboard"

- hosts: www
  roles:
    - mint-v2
